name: xml
description: A lightweight XML Parser.
version: 0.9.2
author: John Evans <prujohn@gmail.com>
homepage: https://github.com/prujohn/dart-xml
dependencies:
  unittest: ">=0.3.5+1 <0.3.6"
  browser: 0.4.1