name: xml
version: 0.9.3+5
author: John Evans <prujohn@gmail.com>
description: A lightweight XML Parser.
homepage: https://github.com/prujohn/dart-xml
dependencies:
  browser: '>=0.4.1'
  unittest: '>=0.5.5'
